/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author JC160300
 */
public class EditRecord extends javax.swing.JFrame {

    /**
     * Creates new form EditRecord
     */
    public EditRecord() {
        initComponents();
        show_call();
        firstNameEdit.setDocument(new Database.JTextFieldLimit(35));
        surnameEdit.setDocument(new Database.JTextFieldLimit(35));
        originEdit.setDocument(new Database.JTextFieldLimit(3));
        ethnicEdit.setDocument(new Database.JTextFieldLimit(20));
        locationEdit.setDocument(new Database.JTextFieldLimit(35));
        outcomeEdit.setDocument(new Database.JTextFieldLimit(20));
        reportEdit.setDocument(new Database.JTextFieldLimit(20));
        arrestEdit.setDocument(new Database.JTextFieldLimit(20));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crimeEditSection = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        editCrimeTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateEdit = new javax.swing.JTextField();
        reportEdit = new javax.swing.JTextField();
        locationEdit = new javax.swing.JTextField();
        outcomeEdit = new javax.swing.JTextField();
        crimeUpdateButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        idEdit = new javax.swing.JTextField();
        personEditSection = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        editPersonTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        personIdEdit = new javax.swing.JTextField();
        firstNameEdit = new javax.swing.JTextField();
        surnameEdit = new javax.swing.JTextField();
        dobEdit = new javax.swing.JTextField();
        ethnicEdit = new javax.swing.JTextField();
        originEdit = new javax.swing.JTextField();
        convictionEdit = new javax.swing.JCheckBox();
        personUpdateButton = new javax.swing.JButton();
        operationEditSection = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        editOperationTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        operationUpdateButton = new javax.swing.JButton();
        deleteRecord = new javax.swing.JButton();
        crimeIDEdit = new javax.swing.JTextField();
        personIDEdit = new javax.swing.JTextField();
        arrestEdit = new javax.swing.JTextField();
        opEdit = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        crimeEditSection.setSize(new java.awt.Dimension(700, 260));
        crimeEditSection.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editCrimeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Crime ID", "Date", "Reported From", "Location", "Outcomes"
            }
        ));
        editCrimeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCrimeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(editCrimeTable);

        crimeEditSection.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 14, -1, 190));

        jLabel2.setText("Date");
        crimeEditSection.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, -1, -1));

        jLabel3.setText("Reported From");
        crimeEditSection.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, -1));

        jLabel4.setText("Location");
        crimeEditSection.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));

        jLabel5.setText("Outcomes");
        crimeEditSection.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, -1));

        dateEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateEditActionPerformed(evt);
            }
        });
        crimeEditSection.getContentPane().add(dateEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 51, 88, -1));
        crimeEditSection.getContentPane().add(reportEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 82, 76, -1));
        crimeEditSection.getContentPane().add(locationEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 113, 93, -1));
        crimeEditSection.getContentPane().add(outcomeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 82, -1));

        crimeUpdateButton.setText("Update");
        crimeUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimeUpdateButtonActionPerformed(evt);
            }
        });
        crimeEditSection.getContentPane().add(crimeUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 158, 30));

        jLabel6.setText("ID");
        crimeEditSection.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, -1, -1));

        idEdit.setEditable(false);
        idEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEditActionPerformed(evt);
            }
        });
        crimeEditSection.getContentPane().add(idEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 25, 54, -1));

        personEditSection.setSize(new java.awt.Dimension(950, 320));
        personEditSection.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editPersonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person ID", "First Name", "Last Name", "Date of Birth", "Ethnic Makeup", "Country of Origin", "Prev Convictions"
            }
        ));
        editPersonTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPersonTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(editPersonTable);

        personEditSection.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 48, 684, 164));

        jLabel7.setText("ID");
        personEditSection.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jLabel8.setText("First Name");
        personEditSection.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jLabel9.setText("Last Name");
        personEditSection.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jLabel10.setText("Date of Birth");
        personEditSection.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, -1, -1));

        jLabel11.setText("Ethnic Makeup");
        personEditSection.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel12.setText("Country of Origin");
        personEditSection.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel13.setText("Previous Convictions");
        personEditSection.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        personEditSection.getContentPane().add(personIdEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 22, 36, -1));
        personEditSection.getContentPane().add(firstNameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 48, 129, -1));

        surnameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameEditActionPerformed(evt);
            }
        });
        personEditSection.getContentPane().add(surnameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 74, 130, -1));
        personEditSection.getContentPane().add(dobEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 79, -1));

        ethnicEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ethnicEditActionPerformed(evt);
            }
        });
        personEditSection.getContentPane().add(ethnicEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 113, -1));

        originEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originEditActionPerformed(evt);
            }
        });
        personEditSection.getContentPane().add(originEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 99, -1));

        convictionEdit.setText("Yes");
        personEditSection.getContentPane().add(convictionEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        personUpdateButton.setText("Update");
        personUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personUpdateButtonActionPerformed(evt);
            }
        });
        personEditSection.getContentPane().add(personUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 246, -1, -1));

        operationEditSection.setSize(new java.awt.Dimension(730, 210));
        operationEditSection.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editOperationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Crime ID", "Person ID", "Arrested For", "Operation?"
            }
        ));
        editOperationTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editOperationTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(editOperationTable);

        operationEditSection.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 21, -1, 146));

        jLabel14.setText("Crime ID");
        operationEditSection.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel15.setText("Person ID");
        operationEditSection.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel16.setText("Arrested For");
        operationEditSection.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel17.setText("Operation?");
        operationEditSection.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        operationUpdateButton.setText("Update");
        operationUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationUpdateButtonActionPerformed(evt);
            }
        });
        operationEditSection.getContentPane().add(operationUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        deleteRecord.setText("Delete Record");
        deleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRecordActionPerformed(evt);
            }
        });
        operationEditSection.getContentPane().add(deleteRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        operationEditSection.getContentPane().add(crimeIDEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, -1));

        personIDEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personIDEditActionPerformed(evt);
            }
        });
        operationEditSection.getContentPane().add(personIDEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 74, -1));
        operationEditSection.getContentPane().add(arrestEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, -1));

        opEdit.setText("Yes");
        operationEditSection.getContentPane().add(opEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Edit Operations / Delete Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit Persons");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Would you like to edit a record's contents? Or would you like to delete a record?");

        jButton3.setText("Edit Crimes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        operationEditSection.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        personEditSection.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dateEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateEditActionPerformed

    }//GEN-LAST:event_dateEditActionPerformed

    private void editCrimeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCrimeTableMouseClicked
        //show the data from the table to the text fields
        int i = editCrimeTable.getSelectedRow();
        i = editCrimeTable.convertRowIndexToModel(i);
        TableModel crimeModel = editCrimeTable.getModel();
        idEdit.setText(crimeModel.getValueAt(i, 0).toString());
        dateEdit.setText(crimeModel.getValueAt(i, 1).toString());
        reportEdit.setText(crimeModel.getValueAt(i, 2).toString());
        locationEdit.setText(crimeModel.getValueAt(i, 3).toString());
        outcomeEdit.setText(crimeModel.getValueAt(i, 4).toString());
    }//GEN-LAST:event_editCrimeTableMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        crimeEditSection.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void crimeUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimeUpdateButtonActionPerformed
        try {
            int id = Integer.parseInt(idEdit.getText());
            String reportedFrom = reportEdit.getText();
            String location = locationEdit.getText();
            String outcome = outcomeEdit.getText();

            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date date = df.parse(dateEdit.getText());
           
            //parse date to sql
            if (!dateEdit.getText().equals(df.format(date))) {
                date = null;
                JOptionPane.showMessageDialog(crimeUpdateButton, "Bad date!");
            }
            long longdate = date.getTime();
            java.sql.Date sdate = new java.sql.Date(longdate);
            
            //connections
            String host = "jdbc:derby://localhost:1527/surreypolice";
            String name = "surreypolice";
            String pass = "admin";
            Connection conn = DriverManager.getConnection(host, name, pass);
            PreparedStatement queryCrimes;
            queryCrimes = conn.prepareStatement("UPDATE tblCrimes SET Date = ?, ReportedFrom = ?, Location = ?, Outcomes = ? WHERE crimeID = " + id); //edit the records where the id is
            EditCrimes.ExecPS(queryCrimes, sdate, reportedFrom, location, outcome);
            DefaultTableModel model = (DefaultTableModel) editCrimeTable.getModel();
            model.setRowCount(0);
            show_call();
            JOptionPane.showMessageDialog(crimeUpdateButton, "Records updated!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_crimeUpdateButtonActionPerformed

    private void idEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEditActionPerformed

    private void surnameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameEditActionPerformed

    private void personUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personUpdateButtonActionPerformed
        try {
            int id = Integer.parseInt(idEdit.getText());
            String firstName = firstNameEdit.getText();
            String lastName = surnameEdit.getText();
            String ethnicity = dobEdit.getText();
            String countryOfOrigin = originEdit.getText();
            boolean prevConvictions;
            //check if prevselected is selected
            boolean prevSelected = convictionEdit.isSelected();
            if (prevSelected) {
                prevConvictions = true;
            } else {
                prevConvictions = false;
            }

            DateFormat df = new SimpleDateFormat("yyyy-MM-dd"); //setting the date format
            Date dob = df.parse(dobEdit.getText());
            if (!dobEdit.getText().equals(df.format(dob))) {
                dob = null;
                JOptionPane.showMessageDialog(personUpdateButton, "Bad date!");
            }
            long longdob = dob.getTime();
            java.sql.Date sdob = new java.sql.Date(longdob); //converting date into sql format
            //connect
            String host = "jdbc:derby://localhost:1527/surreypolice";
            String name = "surreypolice";
            String pass = "admin";
            Connection conn = DriverManager.getConnection(host, name, pass);
            PreparedStatement queryPersons;
            queryPersons = conn.prepareStatement("UPDATE tblPersons SET firstName = ?, lastName = ?, dateOfBirth = ?, Ethnicity = ?, countryOfOrigin = ?, prevConvictions = ?  WHERE crimeID = " + id);
            EditPersons.ExecPS(queryPersons, firstName, lastName, sdob, ethnicity, countryOfOrigin, prevConvictions);
           DefaultTableModel model = (DefaultTableModel) editPersonTable.getModel();
            model.setRowCount(0);
            show_call();
            JOptionPane.showMessageDialog(personUpdateButton, "Records updated!"); //...and give a dialog when sucessfully completed.
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_personUpdateButtonActionPerformed

    private void ethnicEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ethnicEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ethnicEditActionPerformed

    private void originEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_originEditActionPerformed

    private void personIDEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personIDEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personIDEditActionPerformed

    private void operationUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationUpdateButtonActionPerformed
        try {
            int id = Integer.parseInt(idEdit.getText());
            String arrestedFor = arrestEdit.getText();
            boolean operation;
            boolean opSelected = opEdit.isSelected();
            if (opSelected) {
                operation = true;
            } else {
                operation = false;
            }

            String host = "jdbc:derby://localhost:1527/surreypolice";
            String name = "surreypolice";
            String pass = "admin";
            Connection conn = DriverManager.getConnection(host, name, pass);
            PreparedStatement queryOperations;
            //updating the records using the query to do so
            queryOperations = conn.prepareStatement("UPDATE tblOperations (CrimeID, PersonID, reportedFor, Operation) VALUES (?, ?, ? ,?)");
            EditOperations.ExecPS(queryOperations, arrestedFor, operation);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_operationUpdateButtonActionPerformed

    private void deleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRecordActionPerformed
        //deleting the record in tblcrimes or tblpersons wil throw an error as they are both on constraints w/ foreign keys, therefore it's tbloperations first 
        try {
            int id = Integer.parseInt(crimeIDEdit.getText());
            String host = "jdbc:derby://localhost:1527/surreypolice";
            String name = "surreypolice";
            String pass = "admin";
            Connection conn = DriverManager.getConnection(host, name, pass);
            PreparedStatement queryPersons, queryCrimes, queryOperations;
            queryOperations = conn.prepareStatement("DELETE FROM tblOperations WHERE crimeID =" + id);
            queryOperations.executeUpdate();
            queryPersons = conn.prepareStatement("DELETE FROM tblPersons WHERE personID =" + id);
            queryPersons.executeUpdate();
            queryCrimes = conn.prepareStatement("DELETE FROM tblCrimes WHERE crimeID =" + id);
            queryCrimes.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) editOperationTable.getModel();
            model.setRowCount(0);
            show_call();
            JOptionPane.showMessageDialog(deleteRecord, "Records deleted!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_deleteRecordActionPerformed

    private void editOperationTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editOperationTableMouseClicked
        int i = editOperationTable.getSelectedRow();
        i = editOperationTable.convertRowIndexToModel(i);
        TableModel opModel = editOperationTable.getModel();
        crimeIDEdit.setText(opModel.getValueAt(i, 0).toString());
        personIDEdit.setText(opModel.getValueAt(i, 1).toString());
        arrestEdit.setText(opModel.getValueAt(i, 2).toString());
        String operation = opModel.getValueAt(i, 3).toString();
        if (operation.equals("true")) {
            opEdit.setSelected(true);
        } else {
            opEdit.setSelected(false);
        }

    }//GEN-LAST:event_editOperationTableMouseClicked

    private void editPersonTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPersonTableMouseClicked
        int i = editPersonTable.getSelectedRow();
        i = editPersonTable.convertRowIndexToModel(i);
        TableModel personModel = editPersonTable.getModel();
        idEdit.setText(personModel.getValueAt(i, 0).toString());
        firstNameEdit.setText(personModel.getValueAt(i, 1).toString());
        surnameEdit.setText(personModel.getValueAt(i, 2).toString());
        dobEdit.setText(personModel.getValueAt(i, 3).toString());
        ethnicEdit.setText(personModel.getValueAt(i, 4).toString());
        originEdit.setText(personModel.getValueAt(i, 5).toString());
        String conviction = personModel.getValueAt(i, 6).toString();
        if (conviction.equals("true")) {
            convictionEdit.setSelected(true);
        } else {
            convictionEdit.setSelected(false);
        }
    }//GEN-LAST:event_editPersonTableMouseClicked

    public void show_call() {
        ArrayList<CallCrime> crimelist = CreateList.crimeList(); //creates the list
        DefaultTableModel crimemodel = (DefaultTableModel) editCrimeTable.getModel(); //this gets the table (which is tblcrimes)
        Object[] rowcrime = new Object[6]; //creating an array to display the rows in order. row lines up to the amount of rows in tblcrimes
        for (int i = 0; i < crimelist.size(); i++) {
            rowcrime[0] = crimelist.get(i).getCrimeID();
            rowcrime[1] = crimelist.get(i).getDate();
            rowcrime[2] = crimelist.get(i).getreportedFrom();
            rowcrime[3] = crimelist.get(i).getLocation();
            rowcrime[4] = crimelist.get(i).getOutcomes();
            crimemodel.addRow(rowcrime);
        }
        ArrayList<CallPersons> personlist = CreateList.personList(); //creates the list
        DefaultTableModel personmodel = (DefaultTableModel) editPersonTable.getModel(); //this gets the table (which is tblpersons)
        Object[] row = new Object[7]; //creating an array to display the rows in order. row lines up to the amount of rows in tblpersons
        for (int i = 0; i < personlist.size(); i++) {
            row[0] = personlist.get(i).getPersonID();
            row[1] = personlist.get(i).getFirstName();
            row[2] = personlist.get(i).getLastName();
            row[3] = personlist.get(i).getDateOfBirth();
            row[4] = personlist.get(i).getEthnicMakeup();
            row[5] = personlist.get(i).getCountyOfOrigin();
            row[6] = personlist.get(i).getPrevConvictions();
            personmodel.addRow(row);
        }
        ArrayList<CallOperations> operationlist = CreateList.operationList(); //creates the list
        DefaultTableModel opmodel = (DefaultTableModel) editOperationTable.getModel(); //this gets the table (which is tbloperations)
        Object[] oprow = new Object[4]; //creating an array to display the rows in order. row lines up to the amount of rows in tbloperations
        for (int i = 0; i < operationlist.size(); i++) {
            oprow[0] = operationlist.get(i).getCrimeID();
            oprow[1] = operationlist.get(i).getPersonID();
            oprow[2] = operationlist.get(i).getreportedFor();
            oprow[3] = operationlist.get(i).getOperation();
            opmodel.addRow(oprow);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arrestEdit;
    private javax.swing.JCheckBox convictionEdit;
    private javax.swing.JFrame crimeEditSection;
    private javax.swing.JTextField crimeIDEdit;
    private javax.swing.JButton crimeUpdateButton;
    private javax.swing.JTextField dateEdit;
    private javax.swing.JButton deleteRecord;
    private javax.swing.JTextField dobEdit;
    private javax.swing.JTable editCrimeTable;
    private javax.swing.JTable editOperationTable;
    private javax.swing.JTable editPersonTable;
    private javax.swing.JTextField ethnicEdit;
    private javax.swing.JTextField firstNameEdit;
    private javax.swing.JTextField idEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField locationEdit;
    private javax.swing.JCheckBox opEdit;
    private javax.swing.JFrame operationEditSection;
    private javax.swing.JButton operationUpdateButton;
    private javax.swing.JTextField originEdit;
    private javax.swing.JTextField outcomeEdit;
    private javax.swing.JFrame personEditSection;
    private javax.swing.JTextField personIDEdit;
    private javax.swing.JTextField personIdEdit;
    private javax.swing.JButton personUpdateButton;
    private javax.swing.JTextField reportEdit;
    private javax.swing.JTextField surnameEdit;
    // End of variables declaration//GEN-END:variables
}
